version: '3.4'

volumes:
  datafiles:

services:
  ingresosml2:
    environment:
      - DBHOST=database
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
    depends_on: 
      - database
    ports:
      - "80"
      - "443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
  database:
      image: mysql:8.0.0
      container_name: ExpertaMySQL
      command: --skip-ssl
      ports:
        - "3305:3306"
      restart: always
      volumes:
        - datafiles:/var/lib/mysql
      environment:
          MYSQL_ROOT_PASSWORD: '123456'
          MYSQL_DATABASE: ExpertaDB