version: '3.4'

services:
  ingresosml2:
    image: ${DOCKER_REGISTRY-}ingresosml2
    build:
      context: .
      dockerfile: Dockerfile
      
  ingresosml2ui:
    image: ${DOCKER_REGISTRY-}ingresosml2ui
    build: 
      context: .
      dockerfile: ../IngresoSML-UI/Dockerfile
